version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/test.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3600
  ApplicationEnd:
    - location: scripts/stop_server.sh
      timeout: 3600
